In [78]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [79]:
text = """
경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n
"""

In [80]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index)+1
print('단어 집합의 크기 : %d'%vocab_size)

단어 집합의 크기 : 12


In [81]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [82]:
sequences = list()
for line in text.split('\n'):
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
        
print('학습에 사용할 샘플의 갯수 : %d' % len(sequences))
print(sequences)

학습에 사용할 샘플의 갯수 : 11
[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [83]:
max_len = max(len(l) for l in sequences)
print("Max len : {}".format(max_len))

Max len : 6


In [84]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [85]:
sequences = np.array(sequences)
x = sequences[:,:-1]
y = sequences[:,-1]
print(x)
print(y)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]
[ 3  1  4  5  1  7  1  9 10  1 11]


In [86]:
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN

In [88]:
embedding_dim = 10
hidden_units = 32

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x,y,epochs=200,verbose=2)

Epoch 1/200
1/1 - 0s - loss: 2.5258 - accuracy: 0.0000e+00 - 468ms/epoch - 468ms/step
Epoch 2/200
1/1 - 0s - loss: 2.5119 - accuracy: 0.0000e+00 - 2ms/epoch - 2ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4985 - accuracy: 0.0909 - 3ms/epoch - 3ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4853 - accuracy: 0.0909 - 3ms/epoch - 3ms/step
Epoch 5/200
1/1 - 0s - loss: 2.4723 - accuracy: 0.0909 - 2ms/epoch - 2ms/step
Epoch 6/200
1/1 - 0s - loss: 2.4593 - accuracy: 0.1818 - 2ms/epoch - 2ms/step
Epoch 7/200
1/1 - 0s - loss: 2.4460 - accuracy: 0.1818 - 2ms/epoch - 2ms/step
Epoch 8/200
1/1 - 0s - loss: 2.4324 - accuracy: 0.3636 - 2ms/epoch - 2ms/step
Epoch 9/200
1/1 - 0s - loss: 2.4184 - accuracy: 0.3636 - 2ms/epoch - 2ms/step
Epoch 10/200
1/1 - 0s - loss: 2.4038 - accuracy: 0.3636 - 2ms/epoch - 2ms/step
Epoch 11/200
1/1 - 0s - loss: 2.3885 - accuracy: 0.3636 - 2ms/epoch - 2ms/step
Epoch 12/200
1/1 - 0s - loss: 2.3725 - accuracy: 0.3636 - 2ms/epoch - 2ms/step
Epoch 13/200
1/1 - 0s - loss: 2.3557 - accuracy: 

Epoch 105/200
1/1 - 0s - loss: 0.6012 - accuracy: 0.8182 - 4ms/epoch - 4ms/step
Epoch 106/200
1/1 - 0s - loss: 0.5902 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 107/200
1/1 - 0s - loss: 0.5793 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 108/200
1/1 - 0s - loss: 0.5686 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 109/200
1/1 - 0s - loss: 0.5579 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 110/200
1/1 - 0s - loss: 0.5474 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 111/200
1/1 - 0s - loss: 0.5369 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 112/200
1/1 - 0s - loss: 0.5266 - accuracy: 0.8182 - 2ms/epoch - 2ms/step
Epoch 113/200
1/1 - 0s - loss: 0.5164 - accuracy: 0.9091 - 2ms/epoch - 2ms/step
Epoch 114/200
1/1 - 0s - loss: 0.5062 - accuracy: 0.9091 - 2ms/epoch - 2ms/step
Epoch 115/200
1/1 - 0s - loss: 0.4962 - accuracy: 0.9091 - 2ms/epoch - 2ms/step
Epoch 116/200
1/1 - 0s - loss: 0.4863 - accuracy: 1.0000 - 2ms/epoch - 2ms/step
Epoch 117/200
1/1 - 0s - loss: 0.4765 - 

In [89]:
def sentence_generation(model, tokenizer, current_word, n):
    init_word = current_word
    sentence = ''
    
    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=5, padding='pre')
        
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis =1)
        
        for word, index in tokenizer.word_index.items():
            if index == result:
                break
                
        current_word = current_word + ' '+word
        sentence = sentence + ' '+word
    
    sentence = init_word + sentence
    return sentence


print(sentence_generation(model, tokenizer, '경마장에', 4))
print(sentence_generation(model, tokenizer, '그의', 2))
print(sentence_generation(model, tokenizer, '가는', 5))
# n을 4,2,5보다 높은 숫자를 줄 경우 다음에 나오는 단어가 무엇인지 배운적이 없어서 임의 예측을 한다.
print(sentence_generation(model, tokenizer, '경마장에', 8))

경마장에 있는 말이 뛰고 있다
그의 말이 법이다
가는 말이 고와야 오는 말이 곱다
경마장에 있는 말이 뛰고 있다 곱다 곱다 말이 말이
